### ISSUE TITLE
Faltando textlive-lang-portugues

### ISSUE THREAD

**Issue by icaromh** [rafasgj/senac-tcc-lyx#1]
![captura de tela de 2016-05-11 10 12 31](https://cloud.githubusercontent.com/assets/3057676/15182059/f310273e-1760-11e6-9ebc-39748e185f2f.png)

Ao instalar o Lyx no ubuntu 14.04 e tentar visualizar o documento exibiu o erro da imagem acima.
**Resolvido** instalando o **texlive-lang-portuguese** com o comando :

`sudo apt-get install texlive-lang-portuguese`

**Comment by rafasgj** [comment]
Adicionado um guia de instalação (INSTALL.md) para evitar esse tipo de problema no futuro.
