### ISSUE TITLE
Faltando texlive-bibtex-extra

### ISSUE THREAD

**Issue by icaromh** [rafasgj/senac-tcc-lyx#2]
![image](https://cloud.githubusercontent.com/assets/3057676/15182294/1ea4a2e8-1762-11e6-9db3-aca3cb2f73b9.png)

Ao Instalar o Lyx no Ubuntu 14.04 aparentemente não foi instalada a biblatex.sty, para corrigir foi necessário instalá-la com:

`sudo apt-get install texlive-bibtex-extra`

**Comment by rafasgj** [comment]
Adicionado um guia de instalação (INSTALL.md) para evitar esse tipo de problema no futuro.
