### ISSUE TITLE
Ao exportar o relatório a tabela ultrapassa os limites

### ISSUE THREAD

**Issue by icaromh** [rafasgj/senac-tcc-lyx#3]
Ao exportar ou pré-visualizar o projeto as tabelas ultrapassam o limite da folha. Mas quando visualiza-se apenas o conteúdo específico ela se ajeita corretamente.

## Tabela ultrapassando
![image](https://cloud.githubusercontent.com/assets/3057676/15194859/7cbc6d32-179b-11e6-87c5-6fac2ef83886.png)

## Tabela correta
![image](https://cloud.githubusercontent.com/assets/3057676/15194894/a7f79422-179b-11e6-9998-705a03ea3397.png)

**Comment by icaromh** [comment]
Exportação e visualização usando **pdflatex**

**Comment by rafasgj** [comment]
Pode anexar o arquivo que gerou esse problema? (conteudo/Definicao_do_Problema.lyx)

**Comment by icaromh** [comment]
Segue 
[Definicao_Do_Problema.lyx.zip](https://github.com/rafasgj/senac-tcc-lyx/files/260200/Definicao_Do_Problema.lyx.zip)

**Comment by rafasgj** [comment]
O comportamento correto é o do documento principal. O erro no documento de conteúdo é a "fonte padrão", que de acordo com a ABNT deve ser 12, mas com a configuração que estava utilizava uma fonte menor (10).

Minha sugestão é inserir uma qubra de linha no título da tabela onde está "Messenger / Whatsapp", utilizando código TeX. Para isso, digite "CTRL+L" (Linux) e entre com o seguinte texto:

> \shortstack{Messenger/\\Whatsapp}

Mas, dado o conteúdo, acho melhor simplesmente remover um dos dois do quadro, e descrever no texto que ambos tem o mesmo comportamento.
