### ISSUE TITLE
Citações longas

### ISSUE THREAD

**Issue by gomes-fdr** [rafasgj/senac-tcc-lyx#6]
Boa tarde professor,
Nos estilos de parágrafos temos duas opções para citações em ambas o documento final(pdf) não assume o padrão exigido pelo Senac, com 4cm de margem a esquerda e alinhado a direita com o restante do texto.

Abraço
Fabiano

**Comment by gomes-fdr** [comment]
Funcionou professor, basta adicionar \begin{citacao} Citação... \end{citacao} lembrando que usando o insert Latex code.

**Comment by rafasgj** [comment]
Como mencinado, o correto é utilizar o código LaTeX (Ctrl+L) e inserir "\begin{citacao}" e ao término da citação "\end{citação}".
