### ISSUE TITLE
Lista de siglas

### ISSUE THREAD

**Issue by gomes-fdr** [rafasgj/senac-tcc-lyx#7]
Existe alguma "facilidade" no Latex e por extensão no Lyx para geração da lista de siglas?

**Comment by gomes-fdr** [comment]
Boa noite professor, fiz uma pequena alteração usando o pacote nomencl do Latex, funcionou bem e ficou simples.
Eu fiz um fork do seu projeto, até porque tenho feito commits das alterações do TCC, caso o senhor queira ver como ficou... não sei como disponibilizar a partir de um fork para este repositório.
Segue meu repo:
https://github.com/gomes-fdr/senac-tcc-lyx

**Comment by rafasgj** [comment]
Boa a idéia, no entanto, como vários alunos utilizam a lista de siglas de forma errada, e a lista é opcional, eu optei (até o momento), por deixar o documento **sem** a lista de siglas.

Marcarei esse _issue_ como um _enhancement_ para repensar a lista de siglas em um momento apropriado.

**Comment by rafasgj** [comment]
Implementada a lista de siglas, pois apesar de eu continuar contra ela, é importante para o curso de Redes que será contemplado com um modelo do LyX.
